language: java
jdk:
- oraclejdk8
services:
- postgresql
install:
- cp src/main/resources/application.travis.properties src/main/resources/application.properties
- cp src/main/resources/database.travis.properties src/main/resources/database.properties
- cp src/main/resources/database.test.travis.properties src/main/resources/database.test.properties
- cp src/main/resources/migrations/environments/development.travis.properties src/main/resources/migrations/environments/development.properties
before_script:
- psql -c 'create database easytests;' -U postgres
- psql -c 'create database easyteststest;' -U postgres
script:
- ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
- ./mvnw checkstyle:check
- ./mvnw migration:up
- ./mvnw test -B
