swagger: "2.0"
info:
  description: ""
  version: "0.0.1"
  title: "Easy Tests"
host: "api.easy-tests"
tags:
  - name: "users"
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /v1/users:
    get:
      summary: List all users
      operationId: listUsers
      tags:
        - users
      responses:
        "200":
          description: An array of users
          schema:
            $ref: '#/definitions/V1Users'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/V1Error'
    post:
      summary: Create a new User
      operationId: createUser
      parameters:
        - name: user
          in: body
          required: true
          description: User that needs to be created
          schema:
            $ref: '#/definitions/V1User'
      tags:
        - users
      responses:
        "400":
          description: Invalid input
          schema:
            $ref: '#/definitions/V1Error'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/V1Error'
    put:
      summary: Update an existing user
      operationId: updateUser
      tags:
        - users
      parameters:
        - name: user
          in: body
          required: true
          description: User that needs to be added instead of the existing              one with the same id
          schema:
            $ref: '#/definitions/V1User'
      responses:
        '400':
          description: Invalid input
          schema:
            $ref: '#/definitions/V1Error'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/V1Error'
  /v1/users/{userId}:
    get:
      summary: Info for a specific user
      operationId: showUserById
      tags:
        - users
      parameters:
        - name: userId
          in: path
          required: true
          description: The id of the user to retrieve
          type: integer
      responses:
        "200":
          description: Expected response to a valid request
          schema:
            $ref: '#/definitions/V1User'
        '400':
          description: The specified user ID is invalid (not a number).
          schema:
            $ref: '#/definitions/V1Error'
        '404':
          description: A user with the specified ID was not found.
          schema:
            $ref: '#/definitions/V1Error'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/V1Error'
  /v1/users/me:
    get:
      summary: Info for current user
      operationId: showCurrentUser
      tags:
        - users
      responses:
        "200":
          description: Current user
          schema:
            $ref: '#/definitions/V1User'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/V1Error'
    delete:
      summary: Delete a user with the specific id
      operationId: deleteUserById
      tags:
        - users
      parameters:
        - name: userId
          in: path
          required: true
          description: The id of the user to delete
          type: integer
      responses:
        '400':
          description: The specified user ID is invalid (not a number)
          schema:
            $ref: '#/definitions/V1Error'
        '404':
          description: A user with the specified ID was not found
          schema:
            $ref: '#/definitions/V1Error'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/V1Error'
  /v1/objects:
    get:
      summary: List all object
      operationId: listObject
      tags:
        - objects
      responses:
        "200":
          description: An array of objects
          schema:
            $ref: '#/definitions/V1Objects'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/V1Error'
  /v1/objects/{objectId}:
    get:
      summary: Info for a specific user
      operationId: showObjectById
      tags:
        - objects
      parameters:
        - name: objectId
          in: path
          required: true
          description: The id of the object to retrieve
          type: integer
      responses:
        "200":
          description: Expected response to a valid request
          schema:
            $ref: '#/definitions/V1Object'
        "404":
          description: unexpected error
          schema:
            $ref: '#/definitions/V1Object'
definitions:
  V1User:
    type: object
    required:
      - firstName
      - lastName
      - surname
      - email
      - isAdmin
      - state
    properties:
      id:
        type: integer
        format: int64
      firstName:
        type: string
      lastName:
        type: string
      surname:
        type: string
      email:
        type: string
      isAdmin:
        type: boolean
      state:
        type: integer
        format: int64
    example:
      id: 1
      firstName: 'Ivan'
      lastName: 'Ivanovich'
      surname: 'Ivanov'
      email: 'Ivanov@gmail.com'
      password: '1244s'
      isAdmin: false
      state: 1
  V1Users:
    type: array
    items:
      $ref: '#/definitions/V1User'
  V1Object:
    required:
      - id
      - firstName
      - lastNname
      - surname
      - email
      - isAdmin
      - state
    properties:
      id:
        type: integer
        format: int64
      firstName:
        type: string
      lastName:
        type: string
      surname:
        type: string
      email:
        type: string
      isAdmin:
        type: boolean
      state:
        type: integer
  V1Objects:
    type: array
    items:
      $ref: '#/definitions/V1Object'
  V1Error:
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
